const {chromium,expect}=require('playwright/test'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{let url=decodeURIComponent(req.url.split('?')[0]);if(url.endsWith('/'))url+='index.html';const p=path.resolve(root,'.'+url);if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(p,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'html':'text/html; charset=utf-8','css':'text/css','js':'text/javascript','pdf':'application/pdf'})[p.split('.').pop()]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});try{const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url())});await p.goto(base);await p.getByRole('link',{name:'円を開く →',exact:true}).click();await expect(p.locator('.concept-card')).toHaveCount(12);await expect(p.locator('.q-card')).toHaveCount(24);await expect(p.locator('.lab:visible')).toHaveCount(3);
await p.locator('#lesson-1 .figure-open').click();await expect(p.locator('dialog')).toBeVisible();await p.getByRole('button',{name:'閉じる',exact:true}).click();await expect(p.locator('dialog')).not.toBeVisible();
await p.locator('#move-reveal').click();await expect(p.locator('#move-result')).toContainText('60°');await p.locator('#move-position').fill('100');await expect(p.locator('#move-reveal')).toHaveAttribute('aria-pressed','false');await p.locator('#move-side').selectOption('minor');await p.locator('#move-reveal').click();await expect(p.locator('#move-result')).toContainText('120°');
for(const k of ['single','inside','outside']){await p.locator('#proof-case').selectOption(k);await expect(p.locator('#proof-prev')).toBeDisabled();for(let i=0;i<3;i++)await p.locator('#proof-next').click();await expect(p.locator('#proof-next')).toBeDisabled();await expect(p.locator('#proof-before')).toContainText('ひとつ前');}
await p.locator('#diameter-reveal').click();await expect(p.locator('#diameter-result')).toContainText('= 90°');await p.locator('#diameter-height').selectOption('1.45');await expect(p.locator('#diameter-reveal')).toHaveAttribute('aria-pressed','false');await p.locator('#diameter-reveal').click();await expect(p.locator('#diameter-result')).toContainText('≈');
async function bounds(){for(const s of await p.locator('svg:visible').all()){const v=await s.evaluate(e=>{const b=e.getBBox(),v=e.viewBox.baseVal,t=e.getScreenCTM();return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,w:v.width,h:v.height,dx:t.a,dy:t.d}});assert(v.x>=-1&&v.y>=-1&&v.right<=v.w+1&&v.bottom<=v.h+1,JSON.stringify(v));assert(Math.abs(v.dx-v.dy)<1e-8);}}
for(const side of ['major','minor'])for(const v of ['0','100']){await p.locator('#move-side').selectOption(side);await p.locator('#move-position').fill(v);await bounds();}for(const x of ['-0.75','0','0.75'])for(const h of ['0.55','1','1.45']){await p.locator('#diameter-x').fill(x);await p.locator('#diameter-height').selectOption(h);await bounds();}
for(const width of [1440,768,390]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#lesson-5').screenshot({path:`test-results/circle/lesson-${width}.png`});await p.locator('#move-lab').screenshot({path:`test-results/circle/move-${width}.png`});}
await p.goto(base+'study/math/circle/index.html#q24');await expect(p.locator('#q24')).toBeFocused();await p.locator('#q24 .solution summary').click();await p.locator('#q24 [data-grade=own]').click();await p.reload();await expect(p.locator('#q24 .q-status')).toHaveText('自力でできた');await bounds();for(const k of ['guide','workbook','answers']){const r=await c.request.get(base+'print/circle-'+k+'.pdf');assert.equal(r.status(),200);assert.equal((await r.body()).subarray(0,4).toString(),'%PDF');}
const nc=await browser.newContext({javaScriptEnabled:false}),np=await nc.newPage();await np.goto(base+'study/math/circle/index.html');await expect(np.locator('.q-card:visible')).toHaveCount(24);await np.locator('#q1 .solution summary').click();await expect(np.locator('#q1 .solution')).toHaveAttribute('open','');await nc.close();await p.goto('file://'+path.join(root,'study/math/circle/index.html'));await expect(p.locator('.lab:visible')).toHaveCount(3);assert.deepEqual(errors,[]);assert.deepEqual(external.filter(u=>!u.startsWith('file:')),[]);console.log('PASS circle browser: navigation, three labs, bounds/equal scale, reveal reset, 390/768/1440px, records, PDF, offline and no-JS');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.close());
