const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom'),M=require('../assets/circle/model.js');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),D=JSON.parse(read('materials/circle/content.json'));
assert.equal(D.questions.length,24);assert.equal(D.lessons.length,12);
// Independently measure with acos, not the production atan2 formula.
for(let a=0;a<360;a+=30)for(let span=20;span<350;span+=30)for(let offset=10;offset<360;offset+=17){const b=a+span,p=a+offset;if(Math.abs(offset-span)<1e-8)continue;const A=M.point(a),B=M.point(b),P=M.point(p);const u=[A.x-P.x,A.y-P.y],v=[B.x-P.x,B.y-P.y];const expected=Math.acos(Math.max(-1,Math.min(1,(u[0]*v[0]+u[1]*v[1])/(Math.hypot(...u)*Math.hypot(...v)))))*180/Math.PI;assert(Math.abs(M.angle(A,P,B)-expected)<1e-7);assert(Math.abs(M.intercepted(a,b,p)/2-expected)<1e-7);}
assert.equal(M.angle(M.point(0),M.point(0),M.point(90)),null);assert.equal(M.intercepted(210,330,210),null);
for(const q of D.questions){const f=q.figure;if(f.a!==undefined){const angle=M.angle(M.point(f.a),M.point(f.p),M.point(f.b));if(f.inscribed!==undefined)assert(Math.abs(angle-f.inscribed)<1e-8,q.id);if(f.central)assert(Math.abs(angle-f.central/2)<1e-8,q.id);}}
for(const [a,b,p,x,y] of [[226,340,90,22,35],[210,330,190,80,20]]){const P=M.point(p),C=M.point(p+180);assert(Math.abs(M.angle(M.point(a),P,C)-x)<1e-8);assert(Math.abs(M.angle(M.point(b),P,C)-y)<1e-8);}
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),A={x:-3,y:0},B={x:2,y:Math.sqrt(12)},C={x:8,y:0},E={x:-3,y:-Math.sqrt(27)},O={x:2.5,y:-Math.sqrt(27)/2};for(const P of [A,B,C,E])assert(Math.abs(dist(P,O)-Math.sqrt(37))<1e-8);assert(Math.abs(dist(A,{x:0,y:0})/dist(E,{x:0,y:0})-.5)<1e-8);assert(Math.abs(dist(B,{x:0,y:0})/dist(C,{x:0,y:0})-.5)<1e-8);
function make(saved,blocked=false){const d=new JSDOM(read('study/math/circle/index.html'),{url:'https://example.test/study/math/circle/index.html',runScripts:'outside-only'}),w=d.window;if(saved)w.localStorage.setItem('family-circle-v1',saved);w.localStorage.setItem('family-similarity-v1','untouched');if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('blocked')}});w.eval(read('assets/circle/model.js'));w.eval(read('assets/circle/app.js'));return d;}
let d=make(),w=d.window,doc=w.document;const $=s=>doc.querySelector(s),change=(s,v,event='input')=>{$(s).value=v;$(s).dispatchEvent(new w.Event(event,{bubbles:true}));};
for(const q of D.questions){const card=$('#q'+q.id);assert.equal(card.querySelector('.q-prompt').textContent,q.prompt);assert(card.querySelector('.solution').textContent.includes(q.answer));}
$('#move-reveal').click();assert($('#move-result').textContent.includes('60°'));change('#move-side','minor','change');assert.equal($('#move-reveal').getAttribute('aria-pressed'),'false');$('#move-reveal').click();assert($('#move-result').textContent.includes('120°'));
for(const k of ['single','inside','outside']){change('#proof-case',k,'change');assert.equal($('#proof-prev').disabled,true);for(let i=0;i<3;i++)$('#proof-next').click();assert.equal($('#proof-next').disabled,true);assert($('#proof-result').textContent.includes(({single:'60°',inside:'114°',outside:'120°'})[k]));}
$('#diameter-reveal').click();assert($('#diameter-result').textContent.includes('90°'));change('#diameter-height','0.55','change');assert.equal($('#diameter-reveal').getAttribute('aria-pressed'),'false');
$('#q1 [data-grade=own]').click();$('#q24 [data-grade=review]').click();assert($('#progress-text').textContent.includes('1 / 24'));assert.equal(w.localStorage.getItem('family-similarity-v1'),'untouched');let saved=w.localStorage.getItem('family-circle-v1');d.window.close();d=make(saved);assert.equal(d.window.document.querySelector('#q1 .q-status').textContent,'自力でできた');d.window.close();d=make('bad json');assert.equal(d.window.document.querySelector('#storage-notice').hidden,false);d.window.close();d=make(null,true);d.window.document.querySelector('#q2 [data-grade=own]').click();assert.equal(d.window.document.querySelector('#q2 .q-status').textContent,'自力でできた');d.window.close();
const dom=new JSDOM(read('study/math/circle/index.html'));for(const e of dom.window.document.querySelectorAll('[href],[src]')){const v=e.getAttribute('href')||e.getAttribute('src');if(v.startsWith('#'))assert(dom.window.document.getElementById(v.slice(1)),v);else if(!/^https?:/.test(v))assert(fs.existsSync(path.resolve(root,'study/math/circle',v.split('#')[0])),v);}dom.window.close();console.log('PASS circle: independent angle theorem checks, 24 source-matched questions, three labs, reveal reset, persistence/isolation/denial and links');
