const {chromium,expect}=require('playwright/test'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');if(!fs.existsSync(p)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.pdf')?'application/pdf':'text/html; charset=utf-8');res.end(fs.readFileSync(p));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({headless:true});try{const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url())});await p.goto(base);await p.getByRole('link',{name:'三平方を開く →',exact:true}).click();await expect(p.locator('.concept-card')).toHaveCount(17);await expect(p.locator('.q-card')).toHaveCount(28);await expect(p.locator('.lab:visible')).toHaveCount(4);
await p.locator('#lesson-1 .figure-open').click();await expect(p.locator('dialog')).toBeVisible();await p.keyboard.press('Escape');await expect(p.locator('dialog')).not.toBeVisible();
async function bounds(){for(const svg of await p.locator('svg:visible').all()){const v=await svg.evaluate(e=>{const b=e.getBBox(),v=e.viewBox.baseVal,t=e.getScreenCTM();return{id:e.id||e.closest('article')?.id,x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,w:v.width,h:v.height,dx:t.a,dy:t.d}});assert(v.x>=-1&&v.y>=-1&&v.right<=v.w+1&&v.bottom<=v.h+1,JSON.stringify(v));assert(Math.abs(v.dx-v.dy)<1e-8);}}
await bounds();await p.locator('#rearrange-reveal').click();await expect(p.locator('#rearrange-result')).toContainText('25');await p.locator('#rearrange-position').fill('50');await expect(p.locator('#rearrange-reveal')).toBeDisabled();await p.locator('#rearrange-right').click();await expect(p.locator('#rearrange-reveal')).toBeEnabled();
for(const a of ['2','5'])for(const t of ['0','50','100']){await p.locator('#rearrange-a').fill(a);await p.locator('#rearrange-position').fill(t);await bounds();}
for(const a of ['2','4'])for(const t of ['60','90','120']){await p.locator('#condition-a').fill(a);await p.locator('#condition-angle').fill(t);await p.locator('#condition-reveal').click();await bounds();}
await p.locator('#find-reveal').click();await expect(p.locator('#find-result')).toContainText('AB = 8');for(const h of ['1','4']){await p.locator('#find-position').fill(h);await bounds();}await p.locator('#find-case').selectOption('parabola');for(const x of ['-3','0','3']){await p.locator('#find-position').fill(x);await p.locator('#find-reveal').click();await bounds();}
for(const h of ['2','12']){await p.locator('#space-height').fill(h);await expect(p.locator('#space-prev')).toBeDisabled();for(let i=0;i<3;i++){await p.locator('#space-next').click();await bounds();}await expect(p.locator('#space-next')).toBeDisabled();}await expect(p.locator('#space-result')).toContainText('ℓ = 13');
for(const width of [1440,768,390]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const id of ['lesson-2','rearrange-lab','condition-lab','find-lab','space-lab'])await p.locator('#'+id).screenshot({path:`test-results/pythagorean/${id}-${width}.png`});}
for(let i=1;i<=28;i++)await p.locator(`#q${i} .solution summary`).click();await bounds();await p.goto(base+'study/math/pythagorean/index.html#q28');await expect(p.locator('#q28')).toBeFocused();await p.locator('#q28 [data-grade=own]').click();await p.reload();await expect(p.locator('#q28 .q-status')).toHaveText('自力でできた');
for(const k of ['guide','workbook','answers']){const r=await c.request.get(base+'print/pythagorean-'+k+'.pdf');assert.equal(r.status(),200);assert.equal((await r.body()).subarray(0,4).toString(),'%PDF');}
const nc=await browser.newContext({javaScriptEnabled:false}),np=await nc.newPage();await np.goto(base+'study/math/pythagorean/index.html');await expect(np.locator('.q-card:visible')).toHaveCount(28);await np.locator('#q1 .solution summary').click();await expect(np.locator('#q1 .solution')).toHaveAttribute('open','');await nc.close();await p.goto('file://'+path.join(root,'study/math/pythagorean/index.html'));await expect(p.locator('.lab:visible')).toHaveCount(4);assert.deepEqual(errors,[]);assert.deepEqual(external.filter(u=>!u.startsWith('file:')),[]);console.log('PASS pythagorean browser: four labs, equal scales/bounds including revealed solutions, extreme values, widths, records, PDF, offline and no-JS');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.close());
