const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom'),M=require('../assets/pythagorean/model.js');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),D=JSON.parse(read('materials/pythagorean/content.json'));
assert.equal(D.questions.length,28);assert.equal(D.lessons.length,16);
const area=ps=>Math.abs(ps.reduce((a,p,i)=>{const q=ps[(i+1)%ps.length];return a+p.x*q.y-p.y*q.x},0))/2;
// Independently verify the rearrangement: rigid triangles, unchanged area and endpoint partitions.
for(let a=2;a<=5;a+=.5)for(const t of [0,.15,.5,.8,1]){const tris=M.layout(a,4,t);for(const tri of tris){assert(Math.abs(area(tri)-a*2)<1e-8);assert(Math.abs(M.distance(tri[0],tri[1])-a)<1e-8);assert(Math.abs(M.distance(tri[0],tri[2])-4)<1e-8);}assert(Math.abs((a+4)**2-tris.reduce((s,p)=>s+area(p),0)-(a*a+16))<1e-8);}
function inside(p,tri){const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);return tri.every((v,i)=>cross(v,tri[(i+1)%3],p)>1e-8);}
for(const t of [0,1]){const tris=M.layout(3,4,t);for(let x=.031;x<7;x+=.137)for(let y=.047;y<7;y+=.151)assert(tris.filter(tri=>inside({x,y},tri)).length<=1);}
for(let a=2;a<=4;a+=.5)for(let angle=60;angle<=120;angle+=5){const m=M.triangle(a,4,angle);const squared=a*a+16-8*a*Math.cos(angle*Math.PI/180);assert(Math.abs(m.c*m.c-squared)<1e-8);assert.equal(Math.abs(m.c*m.c-(a*a+16))<1e-8,angle===90);}
assert.equal(M.triangle(0,3),null);assert.equal(M.triangle(3,4,180),null);assert.equal(M.chord(5,6),null);assert.equal(M.chord(5,0).length,10);assert.equal(M.chord(5,5).length,0);assert.equal(M.chord(5,3).length,8);
for(let x=-3;x<=3;x+=.5){const p=M.coord(x);assert.equal(p.y,x*x/2);assert(Math.abs(p.square-M.distance(p,{x:0,y:0})**2)<1e-8);}
assert.equal(M.box(3,4,12).diagonal,13);assert.equal(M.box(-3,4,12),null);assert.equal(M.radical(8),'2√2');assert.equal(M.radical(27),'3√3');assert.equal(M.radical(45),'3√5');assert.equal(M.radical(0),'0');
function make(saved,blocked=false){const d=new JSDOM(read('study/math/pythagorean/index.html'),{url:'https://example.test/study/math/pythagorean/index.html',runScripts:'outside-only'}),w=d.window;if(saved)w.localStorage.setItem('family-pythagorean-v1',saved);w.localStorage.setItem('family-circle-v1','untouched');if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('denied')}});w.eval(read('assets/pythagorean/model.js'));w.eval(read('assets/pythagorean/app.js'));return d;}
let d=make(),w=d.window,doc=w.document;const $=s=>doc.querySelector(s),change=(id,v,e='input')=>{$(id).value=v;$(id).dispatchEvent(new w.Event(e,{bubbles:true}));};
for(const q of D.questions){const card=$('#q'+q.id);assert.equal(card.querySelector('.q-prompt').textContent,q.prompt);assert(card.querySelector('.solution').textContent.includes(q.answer));}
$('#rearrange-reveal').click();assert($('#rearrange-result').textContent.includes('25'));change('#rearrange-position','50');assert($('#rearrange-reveal').disabled);assert.equal($('#rearrange-reveal').getAttribute('aria-pressed'),'false');$('#rearrange-right').click();assert(!$('#rearrange-reveal').disabled);
$('#condition-reveal').click();assert($('#condition-result').textContent.includes('等しい'));change('#condition-angle','60');assert.equal($('#condition-reveal').getAttribute('aria-pressed'),'false');$('#condition-reveal').click();assert($('#condition-result').textContent.includes('等しくない'));
$('#find-reveal').click();assert($('#find-result').textContent.includes('AB = 8'));change('#find-case','parabola','change');assert.equal($('#find-reveal').getAttribute('aria-pressed'),'false');$('#find-reveal').click();assert($('#find-result').textContent.includes('OA = 2√2'));change('#find-position','0');$('#find-reveal').click();assert($('#find-result').textContent.includes('距離は0'));
for(let i=0;i<3;i++)$('#space-next').click();assert($('#space-next').disabled);assert($('#space-result').textContent.includes('ℓ = 13'));assert($('#space-before').textContent.includes('ひとつ前'));change('#space-height','2');assert($('#space-prev').disabled);
$('#q1 [data-grade=own]').click();$('#q28 [data-grade=review]').click();assert($('#progress-text').textContent.includes('1 / 28'));assert.equal(w.localStorage.getItem('family-circle-v1'),'untouched');const saved=w.localStorage.getItem('family-pythagorean-v1');d.window.close();d=make(saved);assert.equal(d.window.document.querySelector('#q1 .q-status').textContent,'自力でできた');d.window.close();d=make('bad json');assert(!d.window.document.querySelector('#storage-notice').hidden);d.window.close();d=make(null,true);d.window.document.querySelector('#q2 [data-grade=own]').click();assert.equal(d.window.document.querySelector('#q2 .q-status').textContent,'自力でできた');d.window.close();
const dom=new JSDOM(read('study/math/pythagorean/index.html'));for(const e of dom.window.document.querySelectorAll('[href],[src]')){const v=e.getAttribute('href')||e.getAttribute('src');if(v.startsWith('#'))assert(dom.window.document.getElementById(v.slice(1)),v);else if(!/^https?:/.test(v))assert(fs.existsSync(path.resolve(root,'study/math/pythagorean',v.split('#')[0])),v);}dom.window.close();console.log('PASS pythagorean: rigid area partition, angle condition, lengths, four labs, 28 source-aligned questions, reveal reset, storage and links');
