const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const {P,sample}=vm.runInNewContext(read('assets/python-pixel-monster/editor.js')+'\n'+read('assets/python-pixel-monster/sample.js')+';({P:PixelMonster,sample:MONSTER_SAMPLE});');
let p=P.check(sample),edited=P.paint(p,0,1,1,'C');
assert.equal(p.frames[0][1][1],'.');assert.equal(edited.frames[0][1][1],'C');
assert.equal(P.mirror(edited,0).frames[0][1][14],'C');
const blink=P.blink(p);assert.equal(blink.frames.length,2);assert.equal(blink.frames[0][5][5],'W');assert.equal(blink.frames[1][5][5],'B');assert.equal(blink.frames[1][6][5],'#');
for(const patch of [{version:true},{size:[16,17]},{durations:[21]},{frames:[['.'.repeat(15)]]},{palette:{'.':[0,0,0,255]}}])assert.throws(()=>P.check({...sample,...patch}));
const fixtures=[p,blink,edited,P.mirror(edited,0)];const ghost=P.clone(blink);ghost.palette.B[3]=90;fixtures.push(ghost);
const py=`import json,sys,tempfile\nfrom pathlib import Path\nsys.path.insert(0,'materials/python-pixel-monster')\nfrom monster_tools import load_project\nwith tempfile.TemporaryDirectory() as tmp:\n p=Path(tmp)/'project.json'\n for f in json.load(sys.stdin):\n  p.write_text(json.dumps(f['project']))\n  frames,times=load_project(p)\n  assert times==f['project']['durations']\n  assert [list(i.tobytes()) for i in frames]==f['pixels']\nprint('PASS browser/Pillow pixel and timing parity')`;
const result=spawnSync('python3',['-c',py],{cwd:root,encoding:'utf8',input:JSON.stringify(fixtures.map(project=>({project,pixels:project.frames.map((_,i)=>P.pixels(project,i))})))});assert.equal(result.status,0,result.stderr);process.stdout.write(result.stdout);
function make(hash='',blocked=false){const d=new JSDOM(read('study/programming/python-pixel-monster/index.html'),{url:'https://example.test/for_KT_family/study/programming/python-pixel-monster/'+hash,runScripts:'outside-only'});d.window.scrollTo=()=>{};d.window.HTMLCanvasElement.prototype.getContext=()=>({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)}),putImageData(){},clearRect(){},drawImage(){}});if(blocked)Object.defineProperty(d.window,'localStorage',{get(){throw Error('blocked');}});else d.window.localStorage.setItem('family-python-maze-robot-v1','keep');d.window.eval(['content','sample','editor','app'].map(f=>read('assets/python-pixel-monster/'+f+'.js')).join('\n'));return d;}
for(const route of ['#play','#setup',...Array.from({length:6},(_,i)=>'#mission-'+(i+1))]){const d=make(route),doc=d.window.document;assert.equal(doc.querySelectorAll('[data-route]').length,8);if(route.startsWith('#mission')){assert.equal(doc.querySelector('.answer-group').open,false);assert(doc.querySelector('.spec pre code'));const cb=doc.querySelector('#done');cb.checked=true;cb.dispatchEvent(new d.window.Event('change'));assert.equal(JSON.parse(d.window.localStorage.getItem('family-python-pixel-monster-v1')).done.length,1);assert.equal(d.window.localStorage.getItem('family-python-maze-robot-v1'),'keep');}for(const el of doc.querySelectorAll('[href],[src]')){const ref=el.getAttribute('href')||el.getAttribute('src');if(ref.startsWith('#'))continue;assert(fs.existsSync(path.resolve(root,'study/programming/python-pixel-monster',ref)),ref);}d.window.close();}
let d=make('#play'),doc=d.window.document;assert.equal(doc.querySelectorAll('[data-pixel]').length,256);
doc.querySelector('[data-pixel="0,0"]').click();assert.match(doc.querySelector('#pixel-report').textContent,/113, 87, 223, 255/);doc.querySelector('#undo').click();doc.querySelector('[data-mode=inspect]').click();doc.querySelector('[data-pixel="0,0"]').click();assert.match(doc.querySelector('#pixel-report').textContent,/完全に透明/);
doc.querySelector('#blink').click();assert.match(doc.querySelector('[data-pixel="5,5"]').getAttribute('aria-label'),/ B,/);doc.querySelector('#add-frame').click();assert.equal(doc.querySelectorAll('[data-frame]').length,3);doc.querySelector('#undo').click();assert.equal(doc.querySelectorAll('[data-frame]').length,2);
const duration=doc.querySelector('#duration');duration.value=25;duration.dispatchEvent(new d.window.Event('change'));assert.equal(duration.value,'140');assert.match(doc.querySelector('#notice').textContent,/10ms/);d.window.close();
d=make('#mission-2',true);assert(d.window.document.querySelector('.warning'));d.window.close();
console.log('PASS pixel editor, imports, eight routes, hidden solutions, progress isolation and denied storage');
