const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{spawnSync}=require('node:child_process'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const game=vm.runInNewContext(read('assets/python-dice-vault/game.js')+';VaultGame');
// Compare independently running Python and browser reference over action sequences.
const actions=['roll','roll','bank','buy','roll','roll','roll','bank','buy','roll','roll','bank'];
const fixtures=[];for(let f=1;f<=6;f++){let s=game.fresh();for(const a of actions){s=game.step(s,a,a==='roll'?f:null);const {message,...values}=s;fixtures.push({actions:actions.slice(0,fixtures.length%actions.length+1),face:f,expected:values});}}
const py=`import json,sys\nsys.path.insert(0,'materials/python-dice-vault')\nfrom vault_reference import new_game,next_state\nfor case in json.load(sys.stdin):\n s=new_game()\n for a in case['actions']: s=next_state(s,a,case['face'] if a=='roll' else None)\n s.pop('message')\n assert s==case['expected'], (s,case)\nprint('PASS Python/browser rule parity')`;
const res=spawnSync('python3',['-c',py],{cwd:root,input:JSON.stringify(fixtures),encoding:'utf8'});assert.equal(res.status,0,res.stderr);process.stdout.write(res.stdout);
function make(hash='',blocked=false){const d=new JSDOM(read('study/programming/python-dice-vault/index.html'),{url:'https://example.test/for_KT_family/study/programming/python-dice-vault/'+hash,runScripts:'outside-only'});d.window.scrollTo=()=>{};if(blocked)Object.defineProperty(d.window,'localStorage',{get(){throw Error('blocked');}});else d.window.localStorage.setItem('family-python-dice-jupyter-v1','keep');d.window.eval(read('assets/python-dice-vault/content.js')+'\n'+read('assets/python-dice-vault/game.js')+'\n'+read('assets/python-dice-vault/app.js'));return d;}
for(const route of ['#play','#setup',...Array.from({length:6},(_,i)=>'#mission-'+(i+1))]){const d=make(route),doc=d.window.document;assert.equal(doc.querySelectorAll('[data-route]').length,8);if(route.startsWith('#mission')){assert(doc.querySelector('.spec pre code'));assert.equal(doc.querySelector('.answer-group').open,false);const cb=doc.querySelector('#done');cb.checked=true;cb.dispatchEvent(new d.window.Event('change'));assert.equal(JSON.parse(d.window.localStorage.getItem('family-python-dice-vault-v1')).done.length,1);assert.equal(d.window.localStorage.getItem('family-python-dice-jupyter-v1'),'keep');}
for(const el of doc.querySelectorAll('[href],[src]')){const ref=el.getAttribute('href')||el.getAttribute('src');if(ref.startsWith('#'))continue;assert(fs.existsSync(path.resolve(root,'study/programming/python-dice-vault',ref)),ref);}d.window.close();}
let d=make('#mission-3',true);assert(d.window.document.querySelector('.warning'));d.window.close();
d=make('#play');const doc=d.window.document;doc.querySelector('[data-action=roll]').click();assert.notEqual(doc.querySelector('.vault-message').textContent,'宝を集めよう！');doc.querySelector('#new-game').click();assert.equal(doc.querySelector('.vault-message').textContent,'宝を集めよう！');d.window.close();
for(const name of ['vault_lab.ipynb','vault_answers.ipynb']){const n=JSON.parse(read('materials/python-dice-vault/'+name));assert.equal(n.nbformat,4);assert(n.cells.every(c=>c.cell_type!=='code'||c.execution_count===null));}
console.log('PASS vault: 8 routes, hidden solutions, progress isolation, denied storage, demo actions, downloads, notebooks');
