const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');const game=vm.runInNewContext(read('assets/python-maze-robot/game.js')+';MazeRobot');
const fixtures=[];for(let i=0;i<12;i++){const grid=i===0?game.SAMPLE:game.generate(i);const scan=game.search(grid,[1,1],[11,1]);const actions=Array.from({length:30},(_,j)=>['right','down','left','up','wait'][(j*j+i)%5]);let s=game.fresh(grid);for(const a of actions)s=game.turn(s,a);fixtures.push({grid,scan,actions,state:s});}
const py=`import json,sys\nsys.path.insert(0,'materials/python-maze-robot')\nimport maze_reference as m\nfor f in json.load(sys.stdin):\n p,o=m.find_path(f['grid'],(1,1),(11,1))\n assert json.loads(json.dumps(dict(path=p,order=o)))==f['scan']\n s=m.new_game(f['grid'],(1,1),(11,1),(1,9))\n for a in f['actions']:s=m.take_turn(s,a)\n assert json.loads(json.dumps(s))==f['state']\nprint('PASS Python/browser BFS and pursuit parity')`;
const res=spawnSync('python3',['-c',py],{cwd:root,input:JSON.stringify(fixtures),encoding:'utf8'});assert.equal(res.status,0,res.stderr);process.stdout.write(res.stdout);
function make(hash='',blocked=false){const d=new JSDOM(read('study/programming/python-maze-robot/index.html'),{url:'https://example.test/for_KT_family/study/programming/python-maze-robot/'+hash,runScripts:'outside-only'});d.window.scrollTo=()=>{};if(blocked)Object.defineProperty(d.window,'localStorage',{get(){throw Error('blocked');}});else d.window.localStorage.setItem('family-python-dice-vault-v1','keep');d.window.eval(read('assets/python-maze-robot/content.js')+'\n'+read('assets/python-maze-robot/game.js')+'\n'+read('assets/python-maze-robot/app.js'));return d;}
for(const route of ['#play','#setup',...Array.from({length:6},(_,i)=>'#mission-'+(i+1))]){const d=make(route),doc=d.window.document;assert.equal(doc.querySelectorAll('[data-route]').length,8);if(route.startsWith('#mission')){assert.equal(doc.querySelector('.answer-group').open,false);assert(doc.querySelector('.spec pre code'));const cb=doc.querySelector('#done');cb.checked=true;cb.dispatchEvent(new d.window.Event('change'));assert.equal(JSON.parse(d.window.localStorage.getItem('family-python-maze-robot-v1')).done.length,1);assert.equal(d.window.localStorage.getItem('family-python-dice-vault-v1'),'keep');}for(const el of doc.querySelectorAll('[href],[src]')){const ref=el.getAttribute('href')||el.getAttribute('src');if(ref.startsWith('#'))continue;assert(fs.existsSync(path.resolve(root,'study/programming/python-maze-robot',ref)),ref);}d.window.close();}
let d=make('#play'),doc=d.window.document;
doc.querySelector('#scan-step').click();assert.equal(doc.querySelector('#visited-count').textContent,'1');doc.querySelector('#scan-end').click();assert.match(doc.querySelector('#lab-status').textContent,/最短/);assert(doc.querySelectorAll('.maze-cell.path').length>0);
doc.querySelector('[data-mode=edit]').click();doc.querySelector('[data-cell="10,1"]').click();doc.querySelector('[data-cell="11,2"]').click();doc.querySelector('[data-mode=explore]').click();doc.querySelector('#scan-end').click();assert.match(doc.querySelector('#lab-status').textContent,/道がない/);
doc.querySelector('#sample').click();const tab=doc.querySelector('[data-mode=game]');tab.click();tab.dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('#move-count').textContent,'1');doc.querySelector('#game-reset').click();assert.equal(doc.querySelector('#move-count').textContent,'0');d.window.close();
d=make('#mission-3',true);assert(d.window.document.querySelector('.warning'));d.window.close();
for(const name of ['maze_lab.ipynb','maze_answers.ipynb']){const nb=JSON.parse(read('materials/python-maze-robot/'+name));assert.equal(nb.nbformat,4);assert(nb.cells.every(c=>c.cell_type!=='code'||c.execution_count===null));}
console.log('PASS maze: eight routes, exploration steps/path/no route, wall editing, keyboard game, completion isolation/denied storage, download links and notebooks');
