const {chromium}=require('playwright'),{expect}=require('playwright/test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(req.url.split('?')[0]);if(pathname.endsWith('/'))pathname+='index.html';const f=path.resolve(root,'.'+pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'html':'text/html; charset=utf-8','js':'text/javascript','css':'text/css','svg':'image/svg+xml','pdf':'application/pdf'})[f.split('.').pop()]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;const browser=await chromium.launch({headless:true});try{const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(base);await expect(page.locator('h1')).toContainText('家族の');await page.screenshot({path:path.join(out,'family-home-desktop.png'),fullPage:true});await page.getByRole('link',{name:'二次関数を開く →',exact:true}).click();await expect(page.locator('h1')).toContainText('二次関数');
await page.locator('#shape-a').selectOption('-2');await page.locator('#shape-x').fill('-3');await expect(page.locator('#shape-result')).toContainText('y = −18');await page.locator('[data-range="down"]').click();await expect(page.locator('#range-result')).toContainText('−18 ≤ y ≤ 0');await page.locator('#range-left').fill('3');await expect(page.locator('#range-result')).toContainText('−18 ≤ y ≤ −18');await page.locator('[data-range="cross"]').click();
await page.locator('[data-rate="first"]').click();await expect(page.locator('#rate-result')).toContainText('3 ÷ 1 = 3');await page.locator('[data-rate="second"]').click();await expect(page.locator('#rate-result')).toContainText('5 ÷ 1 = 5');await page.locator('[data-rate="symmetric"]').click();await expect(page.locator('#rate-result')).toContainText('0 ÷ 4 = 0');await page.locator('#rate-left').fill('2.5');await expect(page.locator('#rate-right')).toHaveValue('3');await page.locator('#rate-right').fill('-2.5');await expect(page.locator('#rate-left')).toHaveValue('-3');
await page.locator('#q1 .solution summary').click();await page.locator('#q1 [data-grade="own"]').click();await page.reload();await expect(page.locator('#q1 .q-status')).toHaveText('自力でできた');
for(const [stage,count] of Object.entries({start:6,basic:6,graph:4,'range-rate':8,apply:4,finish:6,challenge:4,retry:6})){await page.locator(`[data-stage="${stage}"]`).click();await expect(page.locator('.q-card')).toHaveCount(count);if(stage==='graph'){await page.locator('#q13 .solution summary').click();await expect(page.locator('#q13-answer-plot')).toBeVisible();await page.locator('#q13').screenshot({path:path.join(out,'quadratic-graph-question.png')});}if(stage==='challenge'){await page.locator('#q38 .solution summary').click();await expect(page.locator('#q38 .working')).toContainText('15');await page.locator('#q38').screenshot({path:path.join(out,'quadratic-advanced-answer.png')});}}
await page.getByRole('link',{name:'問39 →',exact:true}).click();await expect(page.locator('#q39')).toBeFocused();await page.locator('#q39 [data-grade="review"]').click();await expect(page.locator('#retry-links')).toContainText('問39');
for(const id of ['shape','range','rate','apply']){await page.goto(base+'study/math/quadratic-functions/#'+id);await page.locator('#'+id).screenshot({path:path.join(out,'quadratic-'+id+'-desktop.png')});}
await page.setViewportSize({width:390,height:844});for(const route of ['','study/','study/math/','questions/','study/math/quadratic-functions/']){await page.goto(base+route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),route+' overflow');await page.screenshot({path:path.join(out,(route||'family-home').replaceAll('/','-')+'mobile.png'),fullPage:true});}
for(const stage of ['graph','range-rate','challenge']){await page.locator(`[data-stage="${stage}"]`).click();await page.locator('.solution summary').last().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),stage+' overflow');}
for(const pdf of ['guide','workbook','answers']){const r=await ctx.request.get(base+'print/quadratic-functions-'+pdf+'.pdf');assert.equal(r.status(),200);assert.equal((await r.body()).subarray(0,4).toString(),'%PDF');}
await page.goto(base+'#practice/start');await expect(page).toHaveURL(/study\/math\/square-roots\/index.html#practice\/start$/);await expect(page.locator('.question-card')).toHaveCount(8);await page.getByRole('link',{name:'← 家族のまなび帳',exact:true}).click();await expect(page.locator('h1')).toContainText('家族の');
const blocked=await browser.newContext();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('denied');}}));const bp=await blocked.newPage();await bp.goto(base+'study/math/quadratic-functions/');await expect(bp.locator('#storage-notice')).toBeVisible();await bp.locator('#q1 [data-grade="own"]').click();await expect(bp.locator('#q1 .q-status')).toHaveText('自力でできた');await blocked.close();
const offline=await browser.newContext(),op=await offline.newPage();await op.goto('file://'+path.join(root,'study/math/quadratic-functions/index.html'));await expect(op.locator('#shape-result')).toContainText('y = 4');await op.locator('[data-stage="graph"]').click();await expect(op.locator('#q14-plot')).toBeVisible();await offline.close();
assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(base)));console.log('PASS quadratic browser: family navigation, 3 explorers, boundaries, 44 questions, graph answers, grade reload, retry navigation, mobile, old links, PDFs, blocked storage and offline.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
