const {chromium}=require('playwright'),{expect}=require('playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=path.resolve(root,'.'+p);if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'html':'text/html; charset=utf-8','js':'text/javascript','css':'text/css','pdf':'application/pdf'})[f.split('.').pop()]||'application/octet-stream');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,url=base+'study/math/similarity/index.html';const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{})});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url());});await page.goto(base);await page.getByRole('link',{name:'相似を開く →',exact:true}).click();await expect(page.locator('h1')).toContainText('相似');await expect(page.locator('.lab.interactive:visible')).toHaveCount(4);
 await expect(page.locator('.concept-card')).toHaveCount(18);
 for(const card of await page.locator('.concept-card').all()){
  await expect(card.locator('.reading-step')).toHaveCount(3);
  const box=await card.locator('svg').evaluate(s=>{const b=s.getBBox(),v=s.viewBox.baseVal;return {x:b.x,y:b.y,right:b.x+b.width,bottom:b.y+b.height,w:v.width,h:v.height};});
  assert(box.x>=0&&box.y>=0&&box.right<=box.w&&box.bottom<=box.h,JSON.stringify(box));
 }
 await page.locator('#parallel .concept-card').nth(1).screenshot({path:path.join(out,'similarity-readability-desktop.png')});
 await page.screenshot({path:path.join(out,'similarity-desktop.png')});
 await page.locator('[data-shape="wide,2"]').click();await expect(page.locator('#shape-result')).toContainText('相似ではない');await page.locator('[data-shape="both,2"]').click();await expect(page.locator('#shape-result')).not.toContainText('相似ではない');
 for(let i=0;i<5;i++){await page.locator(`[data-match="${i}"]`).click();await expect(page.locator('#match-plot')).toContainText(`手順 ${i+1}`);}await page.locator('#match-colors').check();await page.locator('[data-match="1"]').click();
 await page.locator('#parallel-break').click();await expect(page.locator('#parallel-u')).toBeEnabled();await expect(page.locator('#parallel-result')).toContainText('相似とは言えません');await page.locator('#parallel-mid').click();await expect(page.locator('#parallel-u')).toBeDisabled();await page.locator('#parallel-t').fill('0.8');await expect(page.locator('#parallel-u')).toHaveValue('0.8');
 for(const [kind,answer] of [['area','4倍'],['volume','8倍'],['stretch','2倍']]){await page.locator('#scale-kind').selectOption(kind);await expect(page.locator('#scale-reveal')).toHaveAttribute('aria-pressed','false');await page.locator('#scale-reveal').click();await expect(page.locator('#scale-result')).toContainText(answer);}
 await page.locator('#scale-kind').selectOption('volume');await page.locator('#scale-reveal').click();
 for(const id of ['shape','match','parallel','scale'])await page.locator('#'+id+'-lab').screenshot({path:path.join(out,'similarity-'+id+'.png')});
 // Fixed equal x/y scale and figure bounds at all supported extrema/stages.
 for(const id of ['shape','match','parallel','scale']){const m=await page.locator('#'+id+'-plot').evaluate(s=>{const t=s.getScreenCTM();return [t.a,t.d];});assert(Math.abs(m[0]-m[1])<1e-9);}
 for(const mode of ['both','wide'])for(const k of ['0.5','2']){await page.locator('#shape-mode').selectOption(mode);await page.locator('#shape-k').fill(k);await bounds('shape');}
 async function bounds(id){const b=await page.locator('#'+id+'-plot').evaluate(s=>{const r=s.getBBox(),v=s.viewBox.baseVal;return {x:r.x,y:r.y,right:r.x+r.width,bottom:r.y+r.height,w:v.width,h:v.height};});assert(b.x>=-1&&b.y>=-1&&b.right<=b.w+1&&b.bottom<=b.h+1,JSON.stringify({id,b}));}
 for(let i=0;i<5;i++){await page.locator(`[data-match="${i}"]`).click();await bounds('match');}
 for(const kind of ['area','volume','stretch'])for(const k of ['0.5','3']){await page.locator('#scale-kind').selectOption(kind);await page.locator('#scale-k').fill(k);await bounds('scale');}
 await page.locator('#q1 details').first().locator('summary').click();await expect(page.locator('#q1 .solution')).not.toHaveAttribute('open','');await page.locator('#q1 .solution summary').click();await page.locator('#q1 [data-grade=own]').click();await page.reload();await expect(page.locator('#q1 .q-status')).toHaveText('自力でできた');await page.goto(url+'#q31');await expect(page.locator('#q31')).toBeFocused();await page.locator('#q31 [data-grade=review]').click();await expect(page.locator('#review-links')).toContainText('問31');
 for(const width of [390,768]){await page.setViewportSize({width,height:844});await page.goto(url);await page.locator('#parallel .concept-card').nth(1).screenshot({path:path.join(out,`similarity-readability-${width}.png`)});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const id of ['shape','match','parallel','scale']){await page.locator('#'+id+'-lab').screenshot({path:path.join(out,`similarity-${id}-${width}.png`)});}await page.goto(url+'#q28');await page.locator('#q28 .solution summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 for(const kind of ['guide','workbook','answers']){const r=await context.request.get(base+'print/similarity-'+kind+'.pdf');assert.equal(r.status(),200);assert.equal((await r.body()).subarray(0,4).toString(),'%PDF');}
 const blocked=await browser.newContext();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}}));const bp=await blocked.newPage();await bp.goto(url);await expect(bp.locator('#storage-notice')).toBeVisible();await bp.locator('#q1 [data-grade=own]').click();await expect(bp.locator('#q1 .q-status')).toHaveText('自力でできた');await blocked.close();
 const off=await browser.newContext(),op=await off.newPage();await op.goto('file://'+path.join(root,'study/math/similarity/index.html'));await expect(op.locator('.lab.interactive:visible')).toHaveCount(4);await off.close();
 const nojs=await browser.newContext({javaScriptEnabled:false}),np=await nojs.newPage();await np.goto(url);await expect(np.locator('.q-card:visible')).toHaveCount(32);await np.locator('#q32 .solution summary').click();await expect(np.locator('#q32 .solution')).toHaveAttribute('open','');await nojs.close();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS similarity browser: navigation, four labs, bounds/equal scale, reveal reset, solutions, storage, deep links, 390/768/1440 widths, PDFs, blocked storage, offline and no-JS');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
